config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
      }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  layout 'login'
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'login'
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'login'
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
	<div class="header-outs">
		<div id="snow"></div>
		<header>
			<div class="container-fluid px-lg-5 ">
				<nav class="mnu mx-auto">
				<label for="drop" class="toggle">Menu</label>
				<input type="checkbox" id="drop">
					<ul class="menu">
						<li class="mr-lg-0"><a href="#">Home</a></li>
						<li class="mr-lg-0"><a href="#">About</a></li>
						<li class="mr-lg-0"><a href="#">Services</a></li>
						<li class="mr-lg-0"><a href="#">Gallery</a></li>
						<li class="mr-lg-0"><a href="#">Testimonials</a></li>
						<li class="mr-lg-0"><a href="#" class="scroll">Events</a></li>
						<li><a href="#contact">Contact</a></li>
						<% if user_signed_in? %>
						<li class="mr-lg-0">
						<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
						<!-- <li><a href="#{destroy_user_session_path, method: :delete}">Logout</a></li>        -->
						</li>
						<% else %>
						<li class="mr-lg-0">
						<%= link_to('Login', new_user_session_path)  %>
						<!-- <li><a href="#{new_user_session_path}">Login</a></li> -->
						</li>
						<% end %>
					</ul>
				</nav>
			</div>
		</header>

		<div class="style-banner">
			<h1>christmas party</h1>
			<p class="mt-3">Wishing You A Happy Christmas</p>
		</div>
	</div>
		<div class="cpy-right text-center py-3">	
			<p>© 2018 Avinash Group. All rights reserved | Design by
				<a href="http://avinashmehta.herokuapp.com"> Avinash.</a>
			</p>
		</div>
<script>
 addEventListener("load", function () {
 	setTimeout(hideURLbar, 0);
 }, false);
 
 function hideURLbar() {
 	window.scrollTo(0, 1);
 }
</script>

app/views/layouts/_normal_flash.html.erb
<% if notice.present? %>
	<div class="alert alert-success alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= notice %></li>
		</ul>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-danger alert-bordered alert-dismissible">
		<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
		<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
			<li><%= alert %></li>
		</ul>
  </div>
<% end %>

app/views/layouts/_object_flash.html.erb
<% if object.present? %>
	<% if object.errors.any? %>
		<% if object.errors.full_messages.present? %>
		  <div class="alert alert-danger alert-bordered alert-dismissible">
				<button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
				<ul class="list list-square mb-0" style="-webkit-padding-start: 10px!important; -moz-padding-start: 10px!important; -ms-padding-start: 10px!important; -o-padding-start: 10px!important;">
					<% object.errors.full_messages.each do |error_message| %>
						<li><%= error_message %></li>
					<% end %>
				</ul>
		  </div>
	  <% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet">
     <link href="//fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Clear login Form a Responsive Web Template, Bootstrap Web Templates, Flat Web Templates, Android Compatible Web Template, Smartphone Compatible Web Template, Free Webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">

    <script>
      addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
      }, false);

      function hideURLbar() {
        window.scrollTo(0, 1);
      }
    </script>

    <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'login', 'data-turbolinks-track': 'reload' %>

    <meta name="keywords" content="Ribbon Login Form Responsive Templates, Iphone Compatible Templates, Smartphone Compatible Templates, Ipad Compatible Templates, Flat Responsive Templates"/>
    <!-- <link href="css/style.css" rel='stylesheet' type='text/css' /> -->
    <!--webfonts-->
<!--     <link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=devanagari,latin-ext" rel="stylesheet"> -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'> -->
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

<script type="text/javascript">
  $(function() {
    var notice = '<%= flash[:notice].present? ? flash[:notice] : "" %>';
    if(notice != '')
    {
      new PNotify({
        title: 'Notice',
        text: notice,
        icon: 'icon-checkmark3',
        type: 'success',
        addclass: 'bg-success'
      });
    }
    var alert = '<%= flash[:alert].present? ? flash[:alert] : "" %>';
    if(alert != '')
    {
      new PNotify({
        title: 'Alert',
        text: alert,
        icon: 'icon-warning2',
        type: 'error',
        addclass: 'bg-warning'
      });
    }
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>